### PR TITLE
Make PK non-clustered

### PR DESCRIPTION
**Pull request by mihasic**
Should support more non-blocking writers, since inserts would not fall on the same page all the time. Maybe, should make the index with Id a clustered one...

### CODE REVIEW

**Comment by damianh** [comment]
Thanks Mike.

I am assuming this is non-breaking. However, I will need to implement a migration step.

**Comment by mihasic** [comment]
It's not really done... I've created more as a reminder yet.

**Comment by damianh** [comment]
Just for the observers, this will make a performance improvement.

**Comment by damianh** [comment]
Did a bit of a manual load test - definite improvement.

**Pull request merged**
