### PR TITLE
[WIP] Update to support .Net Core

### PR DESCRIPTION
**Pull request by BennieCopeland**
Implementation work for issue #56.

I'm in the process of updating this to support .Net Core. Current effort is focused on targeting frameworks .Net 4.6 and .Net Standard 1.6.

Working on:
- [X] Restructure project into standard .Net Core structure (src and test folders)
- [X] Update SqlStreamStore project to support targeted frameworks
- [X] Update SqlStreamStore.Tests to support targeted frameworks and ensure tests are passing
- [x] Update SqlStreamStore.MsSql to support targeted frameworks
- [x] Update SqlStreamStore.MsSql.Tests to support targeted frameworks and ensure tests are passing
- [x] Update SqlStreamStore.Postgres to support targeted frameworks
- [x] Update SqlStreamStore.Postgres.Tests to support targeted frameworks ~~and ensure tests are passing~~
- [x] Update Example project to support targeted frameworks
- [x] Update cake build process

Not sure about:
- GhostDoc support
- ncrunch support
- ~~SharedAssemblyInfo.cs support~~
- ~~How rebasing will affect my current work~~

### CODE REVIEW

**Comment by BennieCopeland** [comment]
@damianh Can you add the dotnet core cli to the build server?

**Comment by damianh** [comment]
That will happen when the tooling RTMs

**Comment by BennieCopeland** [comment]
Alright, I should be done with this in a couple of days.

**Comment by BennieCopeland** [comment]
@damianh I haven't gotten around to finishing the Postgres projects, but do you have any acceptance criteria for this pull request in addition to what I've listed?

Some things that I would like your input on are:
* Project structure - I moved the projects into /src and /test directories respectively as that is how guidance was for project.json files. Do you want to keep this, or should I revert it back?
* Currently supports .Net 4.6 and .Net Standard 1.3 - .Net Standard 1.3 libraries can be referenced from .Net Framework 4.6 projects and up. Do  you want to continue to target/build both frameworks, or go all in on .Net Standard 1.3? I'm not sure how many previous versions of Visual Studio can use a nuget package that only includes netstandard. I've [asked the question](https://github.com/dotnet/standard/issues/241), but I suspect only VS2015 and up can use netstandard packages.
* Packaging - I've done the best I can to keep the .Net 4.6 nuget packaging the same, but there were some issues I ran into using Project.json. I haven't looked into the new tooling yet to see if the experience is improved. There IS an issue with netstandard not being able to be ILMerged like you're doing with .Net 4.6 though. Additionally, the new nuget tooling creates two packages, one is normal and the other contains the PDB and source files for debugging. The current packaging has everything in one.

**Comment by damianh** [comment]
Bit of an epic PR @BennieCopeland . Will try to have a look this week. Cheers.

**Comment by damianh** [comment]
Just going to hold of this a little bit. There are some changes coming in that are higher priority.

**Comment by damianh** [comment]
@BennieCopeland can you do a rebase please? I'd like to take this forward now prior to 1.0 :)

>  Project structure - I moved the projects into /src and /test directories respectively as that is how guidance was for project.json files. Do you want to keep this, or should I revert it back?

This is the one change that want reverted, I don't agree with that layout (it's not prescribed, just the AspNet team's preference). Please leave all projects flat in the `/src` folder.

> Currently supports .Net 4.6 and .Net Standard 1.3 - .Net Standard 1.3 libraries can be referenced from .Net Framework 4.6 projects and up. Do you want to continue to target/build both frameworks, or go all in on .Net Standard 1.3? 

Very good question... had a think about it and I think it'll be better to target both (from same csproj). Also, netstandard will bring with it a load of nuget packages that .Net 4.6 users will be annoyed with.  I did this with [OwinHttpMessageHandler](https://github.com/damianh/OwinHttpMessageHandler/blob/master/src/OwinHttpMessageHandler/OwinHttpMessageHandler.csproj) 

> but there were some issues I ran into using Project.json

Yeah let's stick with 2017 and new `csproj` format.

> There IS an issue with netstandard not being able to be ILMerged like you're doing with .Net 4.6 though.

Leave it as is. I'll manually merge in the code from the dependencies that I need to work around this.

**Comment by BennieCopeland** [comment]
I'll try to get this done tonight.

**Comment by BennieCopeland** [comment]
Rebased, working on the other items now.

- [ ] Move test projects back to src
- [ ] Move solution file back to src
- [ ] Fix paths in both solution file and test projects
- [ ] Fix paths in build.cake

**Comment by BennieCopeland** [comment]
Did you want to stick to using nuspec files or using the new csproj packaging?

**Comment by damianh** [comment]
Build runs fine locally. I'll investigate the CI problem.

**Comment by damianh** [comment]
Think we'll stick to nuspec for now.

**Comment by BennieCopeland** [comment]
Lol, what changed?

**Comment by damianh** [comment]
I've merged this to `netstandard` branch and done some changes on top of that. We can continue with any further changes we need targeting that branch.

Thanks for the epic PR @BennieCopeland ! Excellent work, very much appreciated.

**Pull request closed without merging**
